<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WarningsAsErrors>nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miniaudio-CS\Miniaudio-CS\Miniaudio-CS.csproj" />
    <ProjectReference Include="..\VoiceChatSharp\VoiceChatSharp.csproj" />
  </ItemGroup>

</Project>
