<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoiceChatSharp.DefaultImplementation\VoiceChatSharp.DefaultImplementation.csproj" />
    <ProjectReference Include="..\VoiceChatSharp\VoiceChatSharp.csproj" />
  </ItemGroup>

</Project>
